# Generated by Django 2.0.5 on 2018-05-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='race',
            new_name='type_pet',
        ),
    ]
