# Generated by Django 2.0.5 on 2018-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20180507_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_pet',
            field=models.ImageField(blank=True, default='profile_pet/default_pet.png', upload_to='profile_pet'),
        ),
    ]
