# Generated by Django 2.0.4 on 2018-05-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_time', models.DateTimeField()),
                ('food_type', models.CharField(choices=[('dog_food', 'comida para perro'), ('cat_food', 'comida para gato'), ('bird_food', 'comida para ave'), ('vitamin_supplement', 'suplementos vitaminicos'), ('medicine', 'medicamentos')], max_length=20)),
                ('quantity', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_time', models.DateTimeField()),
                ('volunteer_type', models.CharField(choices=[('doctor', 'veterinario'), ('staff', 'administrativo'), ('handler', 'cuidador')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
